security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        users_in_db:
            entity: { class: App\Entity\User, property: email }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_db
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout

    access_control:
        # - { path: "^/app", roles: ROLE_ADMIN }
        - { path: "^/admin", roles: ["ROLE_ADMIN", "ROLE_MODERATOR"] }
        - { path: "^/client", roles: ROLE_CLIENT }
